# Generated by Django 2.2.6 on 2019-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dest',
            field=models.CharField(default='dest', max_length=100),
        ),
        migrations.AddField(
            model_name='todolist',
            name='src',
            field=models.CharField(default='src', max_length=100),
        ),
    ]
